# ******************************************************************************
# gitlab-ci.yml file to build and deploy fre-nctools
# ******************************************************************************

before_script:
  - hostname

variables:
  buildDir: build.${FRE_SITE}.${CI_COMMIT_REF_SLUG}
  CONFIG_SITE: ${CI_PROJECT_DIR}/site-configs/${FRE_SITE}/config.site
.buildScript: &buildScript
  script:
    - . ${CI_PROJECT_DIR}/site-configs/${FRE_SITE}/env.sh
    - autoreconf -i
    - mkdir ${buildDir}
    - cd ${buildDir}
    - ../configure --prefix=${FMS_HOME}/local/opt/fre-nctools/test/${FRE_SITE}
    - make
    - make -j check
  artifacts:
    expire_in: 1 month
    paths:
      - ${CI_PROJECT_DIR}/build.${FRE_SITE}.${CI_COMMIT_REF_SLUG}

.deployScript: &deployScript
  script:
    - cd ${CI_PROJECT_DIR}
    - . ${CI_PROJECT_DIR}/site-configs/${FRE_SITE}/env.sh
    - autoreconf -i
    - cd ${CI_PROJECT_DIR}/${buildDir}
    - make install

build:gfdl-ws:
  stage: build
  tags:
    - gfdl-ws
  variables:
    GIT_STRATEGY: clone
    FRE_SITE: gfdl-ws
    FMS_HOME: /home/fms
  <<: *buildScript

build:gfdl:
  stage: build
  tags:
    - gfdl
  variables:
    GIT_STRATEGY: clone
    FRE_SITE: gfdl
    FMS_HOME: /home/fms
  <<: *buildScript

build:ncrc:
  stage: build
  tags:
    - ncrc
  variables:
    GIT_STRATEGY: clone
    FRE_SITE: ncrc
    FMS_HOME: /ncrc/home2/fms
  <<: *buildScript

deploy:gfdl-ws:
  stage: deploy
  tags:
    - gfdl-ws_deploy
  environment:
    name: stage_gfdl-ws
  variables:
    FRE_SITE: gfdl-ws
    FMS_HOME: /home/fms
  only:
    - master
  dependencies:
    - build:gfdl-ws
  <<: *deployScript

deploy:gfdl:
  stage: deploy
  tags:
    - gfdl_deploy
  environment:
    name: stage_gfdl
  variables:
    FRE_SITE: gfdl
    FMS_HOME: /home/fms
  only:
    - master
  dependencies:
    - build:gfdl
  <<: *deployScript

deploy:ncrc:
  stage: deploy
  tags:
    - ncrc_deploy
  environment:
    name: stage_ncrc
  variables:
    FRE_SITE: ncrc
    FMS_HOME: /home/fms
  only:
    - master
  dependencies:
    - build:ncrc
  <<: *deployScript
