name: fre-nctools
channels:
  - conda-forge
  - noaa-gfdl
dependencies:
  - conda-forge::nco
  - conda-forge::libnetcdf
  - conda-forge::netcdf-fortran
  - conda-forge::mpich
  - conda-forge::gfortran
  - conda-forge::python>2
  - conda-forge::numpy
  - conda-forge::pytest
  - conda-forge::libtool
  - conda-forge::autoconf
  - conda-forge::automake
  - conda-forge::hdf5=1.14.*=mpi*
  - conda-forge::openmp
  - conda-forge::tcsh
  - conda-forge::which
