name: fre-nctools
channels:
  - conda-forge
  - noaa-gfdl
dependencies:
  - conda-forge::zlib-ng=2.2.*
  - conda-forge::mpich==4.2.3
  - conda-forge::gsl=2.*
  - conda-forge::netcdf-fortran=4.6.*
  - conda-forge::gcc=13.3.*
  - conda-forge::hdf5=1.14.*=mpi*
  - conda-forge::libnetcdf==4.9.2
  - conda-forge::nco=5.2.*
  - conda-forge::python>2
  - conda-forge::numpy<2
  - conda-forge::pytest
  - conda-forge::libtool
  - conda-forge::autoconf=2.69.*
  - conda-forge::automake=1.16.*
  - conda-forge::tcsh
  - conda-forge::which
  - conda-forge::make=4.2.*
  - conda-forge::coreutils
  - conda-forge::c-compiler
  - conda-forge::tempest-remap!=2.2.0
