name: build_conda
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/noaa-gfdl/fre-nctools-ci-rocky-gnu:14.2.0_v2
#      image: ghcr.io/noaa-gfdl/fre-cli:miniconda24.7.1_gcc14.2.0

    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run Conda to Build
        run: |
          # append the reqd channels
          conda config --append channels conda-forge
          conda config --append channels noaa-gfdl

          # remove any default channels
          conda config --remove channels defaults

          # just in case
          conda config --show channels

          # install conda-build and conda-verify
          conda install conda-forge::conda-build conda-forge::conda-verify

          # conda build
          conda build --no-anaconda-upload .
